AKODJENOU_Hervé/PersonnalProject/GymManagement/routes/web.php
<?php

use App\Http\Controllers\AdherentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CoachsController;
use App\Http\Controllers\CoursController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GymnaseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\SalleController;
use App\Http\Controllers\SeanceController;
use App\Http\Controllers\SeancesController;
use App\Http\Controllers\SearchController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Http\Controllers\AuthenticatedSessionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Principale
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/salles/{salle}', [HomeController::class, 'show'])->name('salle.show');
Route::post('/abonnement', [HomeController::class, 'store'])->name('abonnement.store');
Route::post('/abonnement/adherent', [HomeController::class, 'other'])->name('abonnement.other');



//Connexion
Route::get('/connexion', [AuthenticatedSessionController::class, 'create'])->middleware('guest')->name('login');
Route::post('/connexion', [AuthenticatedSessionController::class, 'store']);

//Déconnexion
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');

//Admin
Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::resource('gymnases', GymnaseController::class);
    Route::resource('managers', ManagerController::class);
});

//Coach
Route::prefix('coach')->middleware('auth')->name('coach.')->group(function () {
});

//Gestionnaire
Route::prefix('manager')->middleware('auth')->name('manager.')->group(function () {
    Route::resource('adherents', AdherentController::class);
    Route::resource('salles', SalleController::class);
    Route::resource('cours', CoursController::class);
    Route::resource('coachs', CoachsController::class);
    Route::get('cours/{cours}/seances/add',[ SeanceController::class,'index'])->name('seance.add');
    Route::post('cours/{cours}/seances/add',[ SeanceController::class,'store'])->name('seance.store');
    Route::delete('cours/{cours}/seances/{seance}',[ SeanceController::class,'delete'])->name('seance.delete');
    Route::post('cours/{cours}/seances/{seance}',[ SeanceController::class,'update'])->name('seance.update');


});

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');


Route::get('/get-communes/{departementId}', [GymnaseController::class, 'loadCommunes']);

// Route::get('/insert', function () {
//     User::create([
//         'role_id' => 1,
//         'nom' => 'AKODJENOU',
//         'prenom' => 'Hervé',
//         'adresse' => 'Abomey-Calavi,Houèto Fifonsi',
//         'telephone' => 66748936,
//         'sexe' => 'Masculin',
//         'date_naissance' => Date::now(),
//         'email' => 'akodjenouherve13@gmail.com',
//         'password' => Hash::make('password'),
//         'photo' => 'photo'
//     ]);
// });

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/admin/gymnases/edit.blade.php
@extends('layouts.app')
@section('title', 'Admin | Modification d\'un gymnase')
@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Modification</h4>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <form action="{{ route('admin.gymnases.update',$gymnase) }}" method="post" class="form"
                                            enctype="multipart/form-data">
                                            @method('PUT')
                                            @csrf
                                            <div class="form-group @error('nom') has-error has-feedback @enderror mt-3">
                                                <label for="nom" class="form-label">Nom </label>
                                                <input type="text" class="form-control" id="nom" name="nom"
                                                    value="{{ old('nom',$gymnase->nom) }}">
                                                @error('nom')
                                                    <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>

                                            <div class="form-group @error('email') has-error has-feedback @enderror mt-3">
                                                <label for="email" class="form-label">Email </label>
                                                <input type="text" class="form-control" id="email" name="email"
                                                    value="{{ old('email',$gymnase->email) }}">
                                                @error('email')
                                                    <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>


                                            <div class="form-group @error('adresse') has-error has-feedback @enderror mt-3">
                                                <label for="adresse" class="form-label">Adresse </label>
                                                <input type="text" class="form-control" id="adresse" name="adresse"
                                                    value="{{ old('adresse',$gymnase->adresse) }}">
                                                @error('adresse')
                                                    <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>
                                            <div
                                                class="form-group @error('description') has-error has-feedback @enderror mt-3">
                                                <label for="description" class="form-label">Description </label>
                                                <textarea class="form-control" id="description" name="description" cols="30">{{ old('description',$gymnase->description) }}</textarea>
                                                @error('description')
                                                    <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>

                                            <div
                                                class="form-group @error('longitude') has-error has-feedback @enderror mt-3">
                                                <label for="longitude" class="form-label">Longitude</label>
                                                <input type="number" class="form-control" id="longitude" name="longitude"
                                                    value="{{ old('longitude',$gymnase->longitude) }}">
                                                @error('longitude')
                                                    <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>
                                            <div
                                                class="form-group @error('latitude') has-error has-feedback @enderror mt-3">
                                                <label for="latitude" class="form-label">Latitude</label>
                                                <input type="number" class="form-control" id="latitude" name="latitude"
                                                    value="{{ old('latitude',$gymnase->latitude) }}">
                                                @error('latitude')
                                                    <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>



                                            <div
                                                class="form-group @error('telephone') has-error has-feedback @enderror mt-3">
                                                <label for="telephone" class="form-label">Télephone </label>
                                                <input type="tel" class="form-control" id="telephone" name="telephone"
                                                    value="{{ old('telephone',$gymnase->telephone) }}">
                                                @error('telephone')
                                                    <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>

                                            <div class="form-group">
                                                <label for="departement" class="form-label">Département</label>
                                                <select id="departement" name="departement" class="form-control">
                                                    @foreach($departements as $departement)
                                                        <option value="{{ $departement->id }}">{{ $departement->nom }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            
                                            <div class="form-group">
                                                <label for="commune" class="form-label">Commune</label>
                                                <select id="commune" name="commune_id" class="form-control"></select>
                                            </div>

                                            <div class="form-group">
												<label for="photo" class="form-label">Photo</label>
												<input type="file" class="form-control-file" id="photo" name="photo">
											</div>

                                            <div class="form-group mt-3">
                                                <label for="ab" class="form-label">Gestionnaire</label>
                                                <select class="form-control" id="ab" name="idgest">
                                                    @foreach ($gestionnaires as $ab)
                                                        <option value="{{ $ab->id }}">{{ $ab->nom }} {{ $ab->prenom }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-primary mt-4">Modifier</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function() {
            $('#basic-datatables').DataTable({});

            $('#multi-filter-select').DataTable({
                "pageLength": 5,
                initComplete: function() {
                    this.api().columns().every(function() {
                        var column = this;
                        var select = $(
                                '<select class="form-control"><option value=""></option></select>'
                            )
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function(d, j) {
                            select.append('<option value="' + d + '">' + d +
                                '</option>')
                        });
                    });
                }
            });

            // Add Row
            $('#add-row').DataTable({
                "pageLength": 5,
            });

            var action =
                '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

            $('#addRowButton').click(function() {
                $('#add-row').dataTable().fnAddData([
                    $("#addName").val(),
                    $("#addPosition").val(),
                    $("#addOffice").val(),
                    action
                ]);
                $('#addRowModal').modal('hide');

            });

            loadCommunes($('#departement').val());

            $('#departement').change(function() {
                // Appel la fonction pour charger les communes à chaque changement de département
                loadCommunes($(this).val());
            });

            function loadCommunes(departementId) {
                // Appel AJAX pour récupérer les communes en fonction du département
                $.ajax({
                    url: '/get-communes/' + departementId,
                    type: 'GET',
                    success: function(data) {
                        // Supprimez les options actuelles du champ Commune
                        $('#commune').empty();

                        // Ajoutez les nouvelles options en fonction des données reçues
                        data.forEach(function(commune) {
                            $('#commune').append('<option value="' + commune.id + '">' + commune.nom + '</option>');
                        });
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            }
        });
    </script>
@endsection

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/admin/gymnases/index.blade.php
@extends('layouts.app')
@section('title', 'Admin | Liste des gymnases')
@section('content')
    <style>
        .empty {
            text-align: center;
            font-weight: bold;
            font-size: 20px;
        }

        .page-title {
            font-size: 21px !important
        }
    </style>
    <div class="main-panel">

        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Liste des gymnases</h4>
                    <a href="{{ route('admin.gymnases.create') }}" class="btn btn-primary fw-bold add"
                        style="font-size: 18px !important">
                        <i class="fas fa-plus-circle"></i>
                        Ajouter
                    </a>
                </div>
                @if (session('successCreate'))
                    <div id="alertS1"></div>
                @endif
                @if (session('successUpdate'))
                    <div id="alertS2"></div>
                @endif
                @if (session('successDelete'))
                    <div id="alertS3"></div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="gymnases-table" class="display table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>#ID</th>
                                                <th>Nom</th>
                                                <th>Adresse</th>
                                                <th>Email</th>
                                                <th class="d-flex justify-content-center">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($gymnases as $data)
                                                <tr>
                                                    <td>{{ $data->id }}</td>
                                                    <td>{{ $data->nom }}</td>
                                                    <td>{{ $data->adresse }}</td>
                                                    <td>{{ $data->email }}</td>
                                                    <td>
                                                        <div class="d-flex gap-2  justify-content-center">
                                                            <a href="{{ route('admin.gymnases.show', $data) }}"
                                                                class="btn btn-success mx-2">
                                                                <i class="far fa-eye" style="font-size: 1.3rem"></i></a>
                                                            <a href="{{ route('admin.gymnases.edit', $data) }}"
                                                                class="btn btn-primary mx-4"><i class="fas fa-edit"
                                                                    style="font-size: 1.3rem"></i></a>
                                                            <form action="{{ route('admin.gymnases.destroy', $data) }}"
                                                                method="post" id="form">
                                                                @csrf
                                                                @method('delete')
                                                                <button class="btn btn-danger show_confirm">
                                                                    <i class="fas fa-trash-alt"
                                                                        style="font-size: 1.3rem"></i>
                                                                </button>
                                                            </form>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    @if ($gymnases->total() == 0)
                                        <div class="empty text-danger  text-center">
                                            Aucune données trouvées
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end mx-5">
                            {{ $gymnases->links('shared.paginator') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection
    @section('script')
        <script>
            function showAlertSuccess(alertId) {
                var alertElement = document.getElementById(alertId);
                if (alertElement) {
                    swal("Succès!", "Le gymnase a été bien crée!", {
                        icon: "success",
                        buttons: {
                            confirm: {
                                className: 'btn btn-success'
                            }
                        },
                    });

                }
            }
            showAlertSuccess('alertS1')

            function showAlertUpdate(alertId) {
                var alertElement = document.getElementById(alertId);
                if (alertElement) {
                    swal("Succès!", "Le gymnase a modifié bien crée!", {
                        icon: "success",
                        buttons: {
                            confirm: {
                                className: 'btn btn-success'
                            }
                        },
                    });

                }
            }
            showAlertUpdate("alertS2");

            function showAlertDelete(alertId) {
                var alertElement = document.getElementById(alertId);
                if (alertElement) {
                    swal("Succès!", "Le gymnase a supprimé bien crée!", {
                        icon: "success",
                        buttons: {
                            confirm: {
                                className: 'btn btn-success'
                            }
                        },
                    });

                }
            }
            showAlertDelete("alertS3");
        </script>
        <script type="text/javascript">
            $('.show_confirm').click(function(event) {
                var form = $(this).closest("form");
                var name = $(this).data("name");
                event.preventDefault();
                swal({
                        title: `Etes-vous sûr de vouloir supprimer ce gymnase?`,
                        icon: "warning",
                        buttons: {
                            cancel: "Annuler",
                            confirm: "Supprimer"
                        },
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            form.submit();
                        }
                    });
            });
        </script>
    @endsection

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/admin/gymnases/show.blade.php
@extends('layouts.app')
@section('title', 'Admin | Détail d\'un gymnase')
@section('content')
    <style>
        .detail * {
            color: white !important;
            font-size: 19px !important
        }

        .titre {
            font-size: 30px !important
        }
    </style>
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Détail</h4>
                </div>
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <div class="card card-post card-round">
                            <img class="card-img-top" src="/assets/img/weight-lifting-1284616_640.jpg" alt="Card image cap">
                            <div class="card-body detail">
                                <h2 class="text-center titre">{{ $gymnase->nom }}</h2>
                                <div class="d-flex justify-content-between">
                                    <div class="info-post ml-2">
                                        <p class="username">Email : </p>
                                        <p class="date text-muted">{{ $gymnase->email }}</p>
                                    </div>
                                    <div class="info-post ml-2">
                                        <p class="username">Gestionnaire : </p>
                                        <p class="date text-muted">{{ $g->nom }} {{ $g->prenom }}</p>
                                    </div>
                                </div>
                                <div class="separator-solid"></div>
                                <p>Département : {{ $dep->nom }} </p>
                                <p>Commune : {{ $commune->nom }} </p>
                                <p>Adresse : {{ $gymnase->adresse }} </p>
                                <p>Description : {{ $gymnase->description }}</p>
                                <p>Longitude : {{ $gymnase->longitude }}</p>
                                <p>Latitude : {{ $gymnase->latitude }}</p>
                                <p>Téléphone : {{ $gymnase->telephone }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function() {
            $('#basic-datatables').DataTable({});

            $('#multi-filter-select').DataTable({
                "pageLength": 5,
                initComplete: function() {
                    this.api().columns().every(function() {
                        var column = this;
                        var select = $(
                                '<select class="form-control"><option value=""></option></select>'
                            )
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function(d, j) {
                            select.append('<option value="' + d + '">' + d +
                                '</option>')
                        });
                    });
                }
            });

            // Add Row
            $('#add-row').DataTable({
                "pageLength": 5,
            });

            var action =
                '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

            $('#addRowButton').click(function() {
                $('#add-row').dataTable().fnAddData([
                    $("#addName").val(),
                    $("#addPosition").val(),
                    $("#addOffice").val(),
                    action
                ]);
                $('#addRowModal').modal('hide');

            });
        });
    </script>
@endsection