AKODJENOU_Hervé/PersonnalProject/GymManagement/routes/web.php
<?php

use App\Http\Controllers\AdherentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CoachsController;
use App\Http\Controllers\CoursController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GymnaseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\SalleController;
use App\Http\Controllers\SeanceController;
use App\Http\Controllers\SeancesController;
use App\Http\Controllers\SearchController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Http\Controllers\AuthenticatedSessionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Principale
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/salles/{salle}', [HomeController::class, 'show'])->name('salle.show');
Route::post('/abonnement', [HomeController::class, 'store'])->name('abonnement.store');
Route::post('/abonnement/adherent', [HomeController::class, 'other'])->name('abonnement.other');



//Connexion
Route::get('/connexion', [AuthenticatedSessionController::class, 'create'])->middleware('guest')->name('login');
Route::post('/connexion', [AuthenticatedSessionController::class, 'store']);

//Déconnexion
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');

//Admin
Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::resource('gymnases', GymnaseController::class);
    Route::resource('managers', ManagerController::class);
});

//Coach
Route::prefix('coach')->middleware('auth')->name('coach.')->group(function () {
});

//Gestionnaire
Route::prefix('manager')->middleware('auth')->name('manager.')->group(function () {
    Route::resource('adherents', AdherentController::class);
    Route::resource('salles', SalleController::class);
    Route::resource('cours', CoursController::class);
    Route::resource('coachs', CoachsController::class);
    Route::get('cours/{cours}/seances/add',[ SeanceController::class,'index'])->name('seance.add');
    Route::post('cours/{cours}/seances/add',[ SeanceController::class,'store'])->name('seance.store');
    Route::delete('cours/{cours}/seances/{seance}',[ SeanceController::class,'delete'])->name('seance.delete');
    Route::post('cours/{cours}/seances/{seance}',[ SeanceController::class,'update'])->name('seance.update');


});

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');


Route::get('/get-communes/{departementId}', [GymnaseController::class, 'loadCommunes']);

// Route::get('/insert', function () {
//     User::create([
//         'role_id' => 1,
//         'nom' => 'AKODJENOU',
//         'prenom' => 'Hervé',
//         'adresse' => 'Abomey-Calavi,Houèto Fifonsi',
//         'telephone' => 66748936,
//         'sexe' => 'Masculin',
//         'date_naissance' => Date::now(),
//         'email' => 'akodjenouherve13@gmail.com',
//         'password' => Hash::make('password'),
//         'photo' => 'photo'
//     ]);
// });

AKODJENOU_Hervé/PersonnalProject/GymManagement/app/Models/Salle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer $id
 * @property string $nom
 * @property string $superficie
 * @property integer $capacite
 * @property string $deleted_at
 * @property string $created_at
 * @property string $updated_at
 * @property integer $gymnase_id
 * @property Gymnase $gymnase
 * @property Contenir[] $contenirs
 * @property Cour[] $cours
 */
class Salle extends Model
{
    use SoftDeletes;
    /**
     * @var array
     */
    protected $fillable = ['nom', 'superficie', 'capacite', 'deleted_at', 'created_at', 'updated_at','gymnase_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function contenirs()
    {
        return $this->hasMany('App\Models\Contenir');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function cours()
    {
        return $this->hasMany('App\Models\Cour');
    }

    public function gymnase()
    {
        return $this->belongsTo('App\Models\Gymnase');
    }
}

AKODJENOU_Hervé/PersonnalProject/GymManagement/app/Http/Controllers/ManagerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ManagerRequest;
use App\Models\Appartenir;
use App\Models\Gymnase;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $manageRoleId = Role::where('nom', 'gestionnaire')->value('id');
        $gestionnaires = User::where('role_id', $manageRoleId)
            ->with('appartenirs.gymnase')
            ->paginate(10);
        // dd($gestionnaires);
        return view('pages.admin.managers.index', compact('gestionnaires'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $manager = User::where('id', $id)
            ->with('appartenirs.gymnase')
            ->get();
        return view('pages.admin.managers.show',compact('manager'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $gymnases = Gymnase::whereDoesntHave('appartenirs.user', function ($query) {
            $query->where('role_id', '2');
        })->get();
        $manager = User::find($id);
        return view('pages.admin.managers.edit', compact('gymnases', 'manager'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ManagerRequest $request, string $id)
    {
        // dd($request->validated());
        User::find($id)->update($request->except('gymnase_id'));

        if ($request->validated('gymnase_id') != null) {
            Appartenir::where('user_id', $id)->update([
                'user_id' => $id,
                'gymnase_id' => $request->validated('gymnase_id'),
            ]);
        }
        return redirect()->route('admin.managers.index')->with('successUpdate', 'Gestionnaire crée avec succès');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Appartenir::where('user_id', $id)->delete();
        User::find($id)->delete();
        return redirect()->route('admin.managers.index')->with('successDelete', 'Gestionnaire suprimé avec succès');
    }
}

AKODJENOU_Hervé/PersonnalProject/GymManagement/app/Http/Controllers/SalleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SalleRequest;
use App\Models\Appartenir;
use App\Models\Salle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SalleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user =  Auth::user();
        if ($user->role->nom == 'Gestionnaire') {
            $appartenance = Appartenir::where('user_id', $user->id)->first();
            $gymnase =  $appartenance->gymnase;

            $salles = Salle::where('gymnase_id', $gymnase->id)->paginate(10);
            return view('pages.manager.salles.index', compact('salles'));
        }
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.manager.salles.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(SalleRequest $request)
    {
        $user =  Auth::user();
        $appartenance = Appartenir::where('user_id', $user->id)->first();
        $gymnase =  $appartenance->gymnase;

        $data = $request->validated();
        $data['gymnase_id'] =  $gymnase->id;
        Salle::create($data);
        return redirect()->route('manager.salles.index')->with('successCreate', 'Salle créee avec succès');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
    }


    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $salle = Salle::find($id);
        return view('pages.manager.salles.edit', compact('salle'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(SalleRequest $request, string $id)
    {
        Salle::find($id)->update($request->validated());
        return redirect()->route('manager.salles.index')->with('successUpdate', 'Salle modifiée avec succès');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Salle::find($id)->delete();
        return redirect()->route('manager.salles.index')->with('successDelete', 'Salle supprimée avec succès');
    }
}

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/manager/salles/create.blade.php
@extends('layouts.app')
@section('title','Manager | Ajout d\'une salle ')
@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Ajouter une nouvelle salle</h4>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <form action="{{ route('manager.salles.store') }}" method="post" class="form" enctype="multipart/form-data">
                                            @csrf
                                
                                            <div class="row">
                                                <div class="form-group col-md-4 @error('nom') has-error has-feedback @enderror mt-3">
                                                    <label for="nom" class="form-label">Nom </label>
                                                    <input type="text" class="form-control" id="nom" name="nom"
                                                    value="{{ old('nom') }}">
                                                    @error('nom')
                                                        <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>
                                                <div class="form-group col-md-4 @error('superficie') has-error has-feedback @enderror mt-3">
                                                    <label for="superficie" class="form-label">Superficie </label>
                                                    <input type="text" class="form-control" id="superficie" name="superficie"
                                                    value="{{ old('superficie') }}">
                                                    @error('superficie')
                                                        <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror           
                                                </div>
                                                <div class="form-group col-md-4 @error('capacite') has-error has-feedback @enderror mt-3">
                                                    <label for="capacite" class="form-label">Capacité </label>
                                                    <input type="number" min="1" class="form-control" id="capacite" name="capacite"
                                                    value="{{ old('capacite') }}">
                                                    @error('capacite')
                                                        <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror           
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-success mt-4">Ajouter</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function() {
            $('#basic-datatables').DataTable({});

            $('#multi-filter-select').DataTable({
                "pageLength": 5,
                initComplete: function() {
                    this.api().columns().every(function() {
                        var column = this;
                        var select = $(
                                '<select class="form-control"><option value=""></option></select>'
                            )
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function(d, j) {
                            select.append('<option value="' + d + '">' + d +
                                '</option>')
                        });
                    });
                }
            });

            // Add Row
            $('#add-row').DataTable({
                "pageLength": 5,
            });

            var action =
                '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

            $('#addRowButton').click(function() {
                $('#add-row').dataTable().fnAddData([
                    $("#addName").val(),
                    $("#addPosition").val(),
                    $("#addOffice").val(),
                    action
                ]);
                $('#addRowModal').modal('hide');

            });
        });
    </script>
@endsection

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/manager/salles/edit.blade.php
@extends('layouts.app')
@section('title','Manager | Modification d\'une salle ')
@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Modification d'une salle</h4>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <form action="{{ route('manager.salles.update',$salle) }}" method="post" class="form" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')
                                            <div class="row">
                                                <div class="form-group col-md-4 @error('nom') has-error has-feedback @enderror mt-3">
                                                    <label for="nom" class="form-label">Nom </label>
                                                    <input type="text" class="form-control" id="nom" name="nom"
                                                    value="{{ old('nom',$salle->nom) }}">
                                                    @error('nom')
                                                        <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>
                                                <div class="form-group col-md-4 @error('superficie') has-error has-feedback @enderror mt-3">
                                                    <label for="superficie" class="form-label">Superficie </label>
                                                    <input type="text" class="form-control" id="superficie" name="superficie"
                                                    value="{{ old('superficie',$salle->superficie) }}">
                                                    @error('superficie')
                                                        <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror           
                                                </div>
                                                <div class="form-group col-md-4 @error('capacite') has-error has-feedback @enderror mt-3">
                                                    <label for="capacite" class="form-label">Capacité </label>
                                                    <input type="number" min="1" class="form-control" id="capacite" name="capacite"
                                                    value="{{ old('capacite',$salle->capacite) }}">
                                                    @error('capacite')
                                                        <span class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror           
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary mt-4">Modifier</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function() {
            $('#basic-datatables').DataTable({});

            $('#multi-filter-select').DataTable({
                "pageLength": 5,
                initComplete: function() {
                    this.api().columns().every(function() {
                        var column = this;
                        var select = $(
                                '<select class="form-control"><option value=""></option></select>'
                            )
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function(d, j) {
                            select.append('<option value="' + d + '">' + d +
                                '</option>')
                        });
                    });
                }
            });

            // Add Row
            $('#add-row').DataTable({
                "pageLength": 5,
            });

            var action =
                '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

            $('#addRowButton').click(function() {
                $('#add-row').dataTable().fnAddData([
                    $("#addName").val(),
                    $("#addPosition").val(),
                    $("#addOffice").val(),
                    action
                ]);
                $('#addRowModal').modal('hide');

            });
        });
    </script>
@endsection

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/manager/salles/index.blade.php
@extends('layouts.app')
@section('title', 'Manager | Liste des salles')
@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Liste des salles</h4>
                    <a href="{{ route('manager.salles.create') }}" class="btn btn-primary fw-bold add"
                        style="font-size: 18px !important">
                        <i class="fas fa-plus-circle"></i>
                        Ajouter
                    </a>
                </div>
                @if (session('successCreate'))
                    <div id="alertS10"></div>
                @endif
                @if (session('successUpdate'))
                    <div id="alertS11"></div>
                @endif
                @if (session('successDelete'))
                    <div id="alertS12"></div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="basic-datatables" class="display table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>#ID</th>
                                                <th>Nom</th>
                                                <th>Superficie</th>
                                                <th>Capacité</th>
                                                <th class="d-flex justify-content-center">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($salles as $data)
                                                <tr>
                                                    <td>{{ $data->id }}</td>
                                                    <td>{{ $data->nom }}</td>
                                                    <td>{{ $data->superficie }}</td>
                                                    <td>{{ $data->capacite }}</td>
                                                    
                                                    <td>
                                                        <div class="d-flex gap-2  justify-content-center">
                                                            
                                                            <a href="{{ route('manager.salles.edit', $data) }}"
                                                                class="btn btn-primary mx-4"><i class="fas fa-edit"
                                                                    style="font-size: 1.3rem"></i></a>
                                                            <form action="{{ route('manager.salles.destroy', $data) }}"
                                                                method="post" id="form">
                                                                @csrf
                                                                @method('delete')
                                                                <button class="btn btn-danger show_confirm_4">
                                                                    <i class="fas fa-trash-alt"
                                                                        style="font-size: 1.3rem"></i>
                                                                </button>
                                                            </form>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>

                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    @if ($salles->total() == 0)
                                        <div class="empty text-danger text-center">
                                            Aucune données trouvées
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end mx-5">
                            {{ $salles->links('shared.paginator') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        function showAlertSuccess(alertId) {
            var alertElement = document.getElementById(alertId);
            if (alertElement) {
                swal("Succès!", "La salle a été bien crée!", {
                    icon: "success",
                    buttons: {
                        confirm: {
                            className: 'btn btn-success'
                        }
                    },
                });

            }
        }
        showAlertSuccess('alertS10')

        function showAlertUpdate(alertId) {
            var alertElement = document.getElementById(alertId);
            if (alertElement) {
                swal("Succès!", "La salle a modifié bien crée!", {
                    icon: "success",
                    buttons: {
                        confirm: {
                            className: 'btn btn-success'
                        }
                    },
                });

            }
        }
        showAlertUpdate("alertS11");

        function showAlertDelete(alertId) {
            var alertElement = document.getElementById(alertId);
            if (alertElement) {
                swal("Succès!", "La salle a supprimé bien crée!", {
                    icon: "success",
                    buttons: {
                        confirm: {
                            className: 'btn btn-success'
                        }
                    },
                });

            }
        }
        showAlertDelete("alertS12");
    </script>
    <script type="text/javascript">
        $('.show_confirm_4').click(function(event) {
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                    title: `Etes-vous sûr de vouloir supprimer cette salle?`,
                    icon: "warning",
                    buttons: {
                        cancel: "Annuler",
                        confirm: "Supprimer"
                    },
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });
    </script>
@endsection