AKODJENOU_Hervé/PersonnalProject/GymManagement/routes/web.php
<?php

use App\Http\Controllers\AdherentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CoachsController;
use App\Http\Controllers\CoursController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GymnaseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\SalleController;
use App\Http\Controllers\SeanceController;
use App\Http\Controllers\SeancesController;
use App\Http\Controllers\SearchController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Http\Controllers\AuthenticatedSessionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Principale
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/salles/{salle}', [HomeController::class, 'show'])->name('salle.show');
Route::post('/abonnement', [HomeController::class, 'store'])->name('abonnement.store');
Route::post('/abonnement/adherent', [HomeController::class, 'other'])->name('abonnement.other');



//Connexion
Route::get('/connexion', [AuthenticatedSessionController::class, 'create'])->middleware('guest')->name('login');
Route::post('/connexion', [AuthenticatedSessionController::class, 'store']);

//Déconnexion
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');

//Admin
Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::resource('gymnases', GymnaseController::class);
    Route::resource('managers', ManagerController::class);
});

//Coach
Route::prefix('coach')->middleware('auth')->name('coach.')->group(function () {
});

//Gestionnaire
Route::prefix('manager')->middleware('auth')->name('manager.')->group(function () {
    Route::resource('adherents', AdherentController::class);
    Route::resource('salles', SalleController::class);
    Route::resource('cours', CoursController::class);
    Route::resource('coachs', CoachsController::class);
    Route::get('cours/{cours}/seances/add',[ SeanceController::class,'index'])->name('seance.add');
    Route::post('cours/{cours}/seances/add',[ SeanceController::class,'store'])->name('seance.store');
    Route::delete('cours/{cours}/seances/{seance}',[ SeanceController::class,'delete'])->name('seance.delete');
    Route::post('cours/{cours}/seances/{seance}',[ SeanceController::class,'update'])->name('seance.update');


});

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');


Route::get('/get-communes/{departementId}', [GymnaseController::class, 'loadCommunes']);

// Route::get('/insert', function () {
//     User::create([
//         'role_id' => 1,
//         'nom' => 'AKODJENOU',
//         'prenom' => 'Hervé',
//         'adresse' => 'Abomey-Calavi,Houèto Fifonsi',
//         'telephone' => 66748936,
//         'sexe' => 'Masculin',
//         'date_naissance' => Date::now(),
//         'email' => 'akodjenouherve13@gmail.com',
//         'password' => Hash::make('password'),
//         'photo' => 'photo'
//     ]);
// });

AKODJENOU_Hervé/PersonnalProject/GymManagement/app/Http/Controllers/ManagerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ManagerRequest;
use App\Models\Appartenir;
use App\Models\Gymnase;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $manageRoleId = Role::where('nom', 'gestionnaire')->value('id');
        $gestionnaires = User::where('role_id', $manageRoleId)
            ->with('appartenirs.gymnase')
            ->paginate(10);
        // dd($gestionnaires);
        return view('pages.admin.managers.index', compact('gestionnaires'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $manager = User::where('id', $id)
            ->with('appartenirs.gymnase')
            ->get();
        return view('pages.admin.managers.show',compact('manager'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $gymnases = Gymnase::whereDoesntHave('appartenirs.user', function ($query) {
            $query->where('role_id', '2');
        })->get();
        $manager = User::find($id);
        return view('pages.admin.managers.edit', compact('gymnases', 'manager'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ManagerRequest $request, string $id)
    {
        // dd($request->validated());
        User::find($id)->update($request->except('gymnase_id'));

        if ($request->validated('gymnase_id') != null) {
            Appartenir::where('user_id', $id)->update([
                'user_id' => $id,
                'gymnase_id' => $request->validated('gymnase_id'),
            ]);
        }
        return redirect()->route('admin.managers.index')->with('successUpdate', 'Gestionnaire crée avec succès');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Appartenir::where('user_id', $id)->delete();
        User::find($id)->delete();
        return redirect()->route('admin.managers.index')->with('successDelete', 'Gestionnaire suprimé avec succès');
    }
}

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/admin/managers/edit.blade.php
@extends('layouts.app')
@section('title', 'Admin | Modification d\'un gestionnaire')
@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Modification</h4>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <form action="{{ route('admin.managers.update', $manager) }}" method="post"
                                            class="form" enctype="multipart/form-data">
                                            @method('PUT')
                                            @csrf

                                            <div class="row">
                                                <div
                                                    class="form-group col-md-6 @error('nom') has-error has-feedback @enderror mt-3">
                                                    <label for="nom" class="form-label">Nom </label>
                                                    <input type="text" class="form-control" id="nom" name="nom"
                                                        value="{{ old('nom', $manager->nom) }}">
                                                    @error('nom')
                                                        <span
                                                            class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>

                                                <div
                                                    class="form-group col-md-6 @error('prenom') has-error has-feedback @enderror mt-3">
                                                    <label for="prenom" class="form-label">Prenom </label>
                                                    <input type="text" class="form-control" id="prenom" name="prenom"
                                                        value="{{ old('nom', $manager->prenom) }}">
                                                    @error('prenom')
                                                        <span
                                                            class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="row">
                                
                                                <div
                                                    class="form-group col-12 @error('adresse') has-error has-feedback @enderror mt-3">
                                                    <label for="adresse" class="form-label">Adresse </label>
                                                    <input type="text" class="form-control" id="adresse" name="adresse"
                                                        value="{{ old('adresse', $manager->adresse) }}">
                                                    @error('adresse')
                                                        <span
                                                            class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="row">

                                                <div
                                                    class="form-group col-md-6 @error('telephone') has-error has-feedback @enderror mt-3">
                                                    <label for="telephone" class="form-label">Télephone </label>
                                                    <input type="tel" class="form-control" id="telephone"
                                                        name="telephone" value="{{ old('telephone', $manager->telephone) }}">
                                                    @error('telephone')
                                                        <span
                                                            class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>


                                                <div class="form-group col-md-6 mt-3">
                                                    <label for="sexe" class="form-label">Sexe</label>
                                                    <select class="form-control" id="sexe" name="sexe">
                                                        <option value="Masculin">Masculin</option>
                                                        <option value="Féminin">Féminin</option>
                                                        <option value="Autre">Autre</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div
                                                    class="form-group col-md-6 @error('date_naissance') has-error has-feedback @enderror ">
                                                    <label for="date_naissance" class="form-label">Date de naissance
                                                    </label>
                                                    <input type="date" class="form-control" id="date_naissance"
                                                        name="date_naissance" value="{{ old('date_naissance',$manager->date_naissance) }}">
                                                    @error('date_naissance')
                                                        <span
                                                            class="form-text text-muted text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>

                                                <div class="form-group col-md-6">
                                                    <label for="departement" class="form-label">Gymnase</label>
                                                    <select id="departement" name="gymnase_id" class="form-control">
                                                        @foreach ($gymnases as $gymnase)
                                                            <option value="{{ $gymnase->id }}">{{ $gymnase->nom }}
                                                            </option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>

                                            <button type="submit" class="btn btn-primary mt-4">Modifier</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function() {
            $('#basic-datatables').DataTable({});

            $('#multi-filter-select').DataTable({
                "pageLength": 5,
                initComplete: function() {
                    this.api().columns().every(function() {
                        var column = this;
                        var select = $(
                                '<select class="form-control"><option value=""></option></select>'
                            )
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function(d, j) {
                            select.append('<option value="' + d + '">' + d +
                                '</option>')
                        });
                    });
                }
            });

            // Add Row
            $('#add-row').DataTable({
                "pageLength": 5,
            });

            var action =
                '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

            $('#addRowButton').click(function() {
                $('#add-row').dataTable().fnAddData([
                    $("#addName").val(),
                    $("#addPosition").val(),
                    $("#addOffice").val(),
                    action
                ]);
                $('#addRowModal').modal('hide');

            });



        });
    </script>
@endsection

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/admin/managers/index.blade.php
@extends('layouts.app')
@section('title', 'Admin | Liste des gestionnaires')
@section('content')
    <style>
        .empty {
            text-align: center;
            font-weight: bold;
            font-size: 20px;
        }

        .page-title {
            font-size: 21px !important
        }
    </style>
    <div class="main-panel">

        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Liste des gestionnaires</h4>
                    
                </div>
                @if (session('successCreate'))
                    <div id="alertS7"></div>
                @endif
                @if (session('successUpdate'))
                    <div id="alertS8"></div>
                @endif
                @if (session('successDelete'))
                    <div id="alertS9"></div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="gymnases-table" class="display table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>#ID</th>
                                                <th>Nom</th>
                                                <th>Prenom</th>
                                                <th>Email</th>
                                                <th>Gymnase</th>
                                                <th class="d-flex justify-content-center">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($gestionnaires as $data)
                                                <tr>
                                                    <td>{{ $data->id }}</td>
                                                    <td>{{ $data->nom }}</td>
                                                    <td>{{ $data->prenom }}</td>
                                                    <td>{{ $data->email }}</td>
                                                    <td>
                                                        @foreach ($data->appartenirs as $appartenir)
                                                            {{ $appartenir->gymnase->nom }}
                                                        @endforeach
                                                    </td>
                                                    <td>
                                                        <div class="d-flex gap-2  justify-content-center">
                                                            <a href="{{ route('admin.managers.show', $data) }}"
                                                                class="btn btn-success mx-2">
                                                                <i class="far fa-eye" style="font-size: 1.3rem"></i></a>
                                                            <a href="{{ route('admin.managers.edit', $data) }}"
                                                                class="btn btn-primary mx-4"><i class="fas fa-edit"
                                                                    style="font-size: 1.3rem"></i></a>
                                                            <form action="{{ route('admin.managers.destroy', $data) }}"
                                                                method="post" id="form">
                                                                @csrf
                                                                @method('delete')
                                                                <button class="btn btn-danger show_confirm_3">
                                                                    <i class="fas fa-trash-alt"
                                                                        style="font-size: 1.3rem"></i>
                                                                </button>
                                                            </form>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    @if ($gestionnaires->total() == 0)
                                        <div class="empty text-danger text-center">
                                            Aucune données trouvées
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end mx-5">
                            {{ $gestionnaires->links('shared.paginator') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection
    @section('script')
        <script>
            function showAlertSuccess(alertId) {
                var alertElement = document.getElementById(alertId);
                if (alertElement) {
                    swal("Succès!", "Le gestionnaire a été bien crée!", {
                        icon: "success",
                        buttons: {
                            confirm: {
                                className: 'btn btn-success'
                            }
                        },
                    });

                }
            }
            showAlertSuccess('alertS7')

            function showAlertUpdate(alertId) {
                var alertElement = document.getElementById(alertId);
                if (alertElement) {
                    swal("Succès!", "Le gestionnaire a modifié bien crée!", {
                        icon: "success",
                        buttons: {
                            confirm: {
                                className: 'btn btn-success'
                            }
                        },
                    });

                }
            }
            showAlertUpdate("alertS8");

            function showAlertDelete(alertId) {
                var alertElement = document.getElementById(alertId);
                if (alertElement) {
                    swal("Succès!", "Le gestionnaire a supprimé bien crée!", {
                        icon: "success",
                        buttons: {
                            confirm: {
                                className: 'btn btn-success'
                            }
                        },
                    });

                }
            }
            showAlertDelete("alertS9");
        </script>
        <script type="text/javascript">
            $('.show_confirm_3').click(function(event) {
                var form = $(this).closest("form");
                var name = $(this).data("name");
                event.preventDefault();
                swal({
                        title: `Etes-vous sûr de vouloir supprimer ce gestionnaire?`,
                        icon: "warning",
                        buttons: {
                            cancel: "Annuler",
                            confirm: "Supprimer"
                        },
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            form.submit();
                        }
                    });
            });
        </script>
    @endsection

AKODJENOU_Hervé/PersonnalProject/GymManagement/resources/views/pages/admin/managers/show.blade.php
@extends('layouts.app')
@section('title', 'Admin | Détail d\'un gestionnaire')
@section('content')
    <style>
        .detail * {
            color: white !important;
            font-size: 19px !important
        }

        .titre {
            font-size: 30px !important
        }
    </style>
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="mt-2 mb-4 d-flex justify-content-between">
                    <h4 class="page-title">Détail</h4>
                </div>
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <div class="card card-post card-round">

                            <div class="card-body detail">
                                @foreach ($manager as $data)
                                    <h2 class="text-center titre">{{ $data->nom }} {{ $data->prenom }}</h2>
                                    <div class="d-flex mt-5 justify-content-between">
                                        <div class="info-post ml-2">
                                            <p class="username">Email : </p>
                                            <p class="date text-muted">{{ $data->email }}</p>
                                        </div>
                                        <div class="info-post ml-2">
                                            <p class="username">Gymnase : </p>
                                            <p class="date text-muted">
                                                @foreach ($data->appartenirs as $appartenir)
                                                    {{ $appartenir->gymnase->nom }}
                                                @endforeach
                                            </p>
                                        </div>
                                    </div>
                                    <div class="separator-solid"></div>
                                    <p>Adresse : {{ $data->adresse }} </p>
                                    <p>Telephone : {{ $data->telephone }} </p>
                                    <p>Sexe : {{ $data->sexe }} </p>
                                    <p>Date de naissance : {{ $data->date_naissance }}</p>
                                    
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function() {
            $('#basic-datatables').DataTable({});

            $('#multi-filter-select').DataTable({
                "pageLength": 5,
                initComplete: function() {
                    this.api().columns().every(function() {
                        var column = this;
                        var select = $(
                                '<select class="form-control"><option value=""></option></select>'
                            )
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function(d, j) {
                            select.append('<option value="' + d + '">' + d +
                                '</option>')
                        });
                    });
                }
            });

            // Add Row
            $('#add-row').DataTable({
                "pageLength": 5,
            });

            var action =
                '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

            $('#addRowButton').click(function() {
                $('#add-row').dataTable().fnAddData([
                    $("#addName").val(),
                    $("#addPosition").val(),
                    $("#addOffice").val(),
                    action
                ]);
                $('#addRowModal').modal('hide');

            });
        });
    </script>
@endsection